### ISSUE TITLE
Picker doesn't open on iOS 8

### ISSUE THREAD

**Issue by leads** [amsul/pickadate.js#523]
The demos on http://amsul.ca/pickadate.js/ do not work properly on iOS 8. I am only testing on an iPad but am aware of similar issues on iPhone. 

The opaque background shows but the position of the calendar is way down at the bottom, so it can mean a lot of scrolling.

iOS 8 possibly changed how it handles CSS position: fixed?

**Comment by hacklover** [comment]
$('.myinput').pickadate({ onOpen: function() { $('.myinput').blur(); } });
also for me, this fixed the problem on iOS 8 and iPad 2

**Comment by amsul** [comment]
@timcreatewell, @izifortune I believe that's related to #609. As long as the picker opens, I believe this issue has been resolved...

**Comment by jokeyrhyme** [comment]
Hi. Great work on reduced this to a fix. The CHANGELOG.md file states that this has been fixed in 3.5.5, but this version has not been tagged or published. Does it look like 3.5.5 will be released soon? Or is it waiting for other work to be completed?

**Comment by jokeyrhyme** [comment]
@samblinkmobile @benbarclay

**Comment by amsul** [comment]
@jokeyrhyme the remaining issues for the 3.5.5 milestone: https://github.com/amsul/pickadate.js/milestones/3.5.5

Cheers.

**Comment by timcreatewell** [comment]
Hi there @amsul, thanks so much for releasing 3.5.5!  I updated my project with the new files this morning but unfortunately (on the iOS simulator at least - iOS 8.1) I'm still seeing the same behaviour: when you choose a year/month from the drop downs (selectYears / selectMonths) the picker (using default style) still scoots to the bottom of the screen.  Or could I be missing something?

**Comment by jokeyrhyme** [comment]
@timcreatewell I'm not sure if this is what you're experiencing, but I have noticed there are still a few layout issues with v3.5.5 on iOS. I've made an unlisted YouTube video here: http://youtu.be/2-Ha45DP2gw
@amsul it seems as though dismissing the pop-up by tapping outside it, instead of pressing the "close" button, makes it more likely (but not 100% likely) to experience weird layout issues.

**Comment by madthew** [comment]
I confirm I have the same issue. Ipad 3 IOS 8.2 datepicker not opening at all it opens just sometimes randomply. android all ok. I tried also the master and also the blur fix but nothing changed.

**Comment by NateWr** [comment]
Hi @amsul, it looks like this thing was never actually fixed. [This solution](https://github.com/amsul/pickadate.js/pull/629#issuecomment-77658806) still seems to work on v3.5.6 as well. Not sure what the solution is here but for now I'm still just commenting out those lines.

**Comment by riccardobevilacqua** [comment]
On iPad Mini with iOS 8.0.2 using v3.5.6, I still got this issue when I try to change date.
Suggested fixes didn't work.
Inspecting the mobile DOM using a MacBook, HTML code looks fine as usual.
The picker nearly behaves like it got a wrong z-index, it's invisible but the dropdowns are touchable.
Tuning CSS was useless.
Any hints, please?

**Comment by ajmueller** [comment]
@riccardobevilacqua is the device you're testing fixed to that version of iOS?  Apple fixed some quirks with iOS 8's version of Safari in later updates.  It's probably worth updating to 8.3 and then testing.

**Comment by riccardobevilacqua** [comment]
Same behaviour on iOS 8.3
